project:
  type: website
  output-dir: docs # Corrected: Indented to the same level as 'type'

website:
  title: "jumper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
